# fly.toml app configuration file generated for church-attendance-app on 2026-07-25T18:55:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'church-attendance-app'
primary_region = 'ewr'

[build]
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source = 'data'
  destination = '/data'

[env]
  ConnectionStrings__Default = 'Data Source=/data/churchattendance.db'
  DataProtectionKeysPath = '/data/dataprotection-keys'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
